				<!-- FOOTER -->

				<footer class="container-fluid pie">
					<div class="container px-0">
						<p class="display-4 text-center pt-5">Contáctanos</p>
						<h4 class="textoVerde text-center pb-4">Te ofrecemos asesoría personalizada y profesional.</h4>
						<br>
						<br>

						<div class="container-fluid p-0">
							<div class="row m-0">

							<div class="col-md-6">
								<form action="contacto/contacto.php" method="post">
										<div class="row">
											<div class="form-group col-12 col-sm-6">
												<input type="text" class="form-control" name="txtNombre" placeholder="Nombre" required/>
											</div>
											<div class="form-group col-12 col-sm-6">
												<input type="email" class="form-control" name="txtCorreo" placeholder="Correo" required/>
											</div>
											<div class="form-group col-12">
												<textarea class="form-control" rows="5" name="txtMensaje" placeholder="Mensaje" required></textarea>
											</div>
											<div class="form-group col-12 col-sm-6 col-lg-4">
												<input type="submit" class="btn btn-outline-secondary btn-lg container-fluid" value="Enviar"/>
											</div>
											<div class="form-group col-12 col-sm-6 col-lg-4">
												<input type="reset" class="btn btn-outline-secondary btn-lg container-fluid" value="Limpiar"/>
											</div>
										</div>
								</form>
							</div>
							<div class="col-md-2">
								<p>
									<br>
									<br>
								</p>
							</div>
							<div class="col-md-4 p-0">
								<div class="container">
									<div class="row">
										<div class="col-2 text-right">
											<i class="fab fa-facebook-square icono"></i>
										</div>
										<div class="col-10 p-0"><a class="text-muted" href="https://www.facebook.com/navapoloconsulting/">facebook.com/navapoloconsulting</a></div>
										<div class="col-12"> <div class="col-md-7"><hr></div></div>
										<div class="col-2 text-right">
											<i class="fab fa-twitter-square icono"></i>
										</div>
										<div class="col-10 p-0"><a class="text-muted" href="https://twitter.com/navapoloconsulting">twitter.com/navapoloconsulting</a></div>
										<div class="col-12"> <div class="col-md-7"><hr></div></div>
										<div class="col-2 text-right">
											<i class="fas fa-phone-square icono"></i>
										</div>
										<div class="col-10 p-0"><a class="text-muted" href="#">(314) 184 0057</a></div>
										<div class="col-12"> <div class="col-md-7"><hr></div></div>
									</div>
								</div>
							</div>
						</div>
							
					</div>
						<hr>

						<div class="row footerTexto">
							<div class="col-md-12 text-muted align-middle my-3">
										<p class="text-center">© navapoloconsulting. Todos los derechos reservados. | Diseñado por: <a href="http://navapoloconsulting.com.mx/" class="text-muted">navapoloconsulting.com.mx</a></p>
							</div>
						</div>
				
					</div>
				</footer>

				<!-- FOOTER -->